name: Trigger auto deployment for cmp-staging-proxy

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cmp-staging-proxy-AutoDeployTrigger-689ff77a-ecf3-416d-9a8c-2edbd39d8230.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CMPSTAGINGPROXY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CMPSTAGINGPROXY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CMPSTAGINGPROXY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/app
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: registryhgvjv1t.azurecr.io
          registryUsername: ${{ secrets.CMPSTAGINGPROXY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CMPSTAGINGPROXY_REGISTRY_PASSWORD }}
          containerAppName: cmp-staging-proxy
          resourceGroup: compellier-dev-rg
          imageToBuild: registryhgvjv1t.azurecr.io/cmp-staging-proxy:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


