name: Trigger auto deployment for containerapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/containerapp-AutoDeployTrigger-f3576fe0-537a-4c60-92b5-4b22c00c6219.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/app
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: compelliercontainerregistry.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: containerapp
          resourceGroup: Compellier
          imageToBuild: compelliercontainerregistry.azurecr.io/containerapp:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


